"""
Django settings for malcom project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import logging
import os
from pathlib import Path

from django.conf.locale.en import formats as en_formats
from django.conf.locale.ja import formats as ja_formats
from django.utils.translation import gettext_lazy as _


def strtobool(val: str | int | bool) -> bool:
    """stringをboolに変換"""
    if isinstance(val, bool):
        return val
    if isinstance(val, str):
        return val.lower() in ["true", "1", "t", "y", "yes"]
    if isinstance(val, int):
        return val == 1
    return bool(val)


# reduce logging output from noisy packages
logging.getLogger("requests").setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("botocore").setLevel(logging.WARNING)
logging.getLogger("s3transfer").setLevel(logging.WARNING)
# ISO 8601, ex: 2008-01-02T10:30:00.000123+02:00
# NOTE: Will not show timezone offset if datetime object is "naive"
ja_formats.DATETIME_FORMAT = "c"
en_formats.DATETIME_FORMAT = "c"


BASE_DIR = Path(__file__).resolve().parent.parent.absolute()

SITE_HEADER = "REPLACE_ME SITE_HEADER"  # noqa: N806
SITE_TITLE = "REPLACE_ME SITE_TITLE"  # noqa: N806
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"  # noqa: N806
DEFAULT_IS_LOCAL_DEVELOPMENT = "False"  # noqa: N806
IS_LOCAL_DEVELOPMENT = bool(strtobool(os.getenv("IS_LOCAL_DEVELOPMENT", DEFAULT_IS_LOCAL_DEVELOPMENT)))

USE_TIMED_TESTRUNNER = strtobool(os.getenv("USE_TIMED_TESTRUNNER", "False"))
if USE_TIMED_TESTRUNNER:
    TEST_RUNNER = "commons.tests.runners.TimedTestRunner"  # noqa: N806
# For CircleCI to generate JUnit XML test reports and optimize test running time
USE_XML_TESTRUNNER = strtobool(os.getenv("USE_XML_TESTRUNNER", "False"))
if not USE_TIMED_TESTRUNNER and USE_XML_TESTRUNNER:
    TEST_RUNNER = "commons.tests.runners.XMLTestRunnerForCI"  # noqa: N806
    TEST_OUTPUT_DIR = "test-reports"  # noqa: N806
    TEST_OUTPUT_FILE_NAME = "results.xml"  # noqa: N806
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "&37^bx2j^ji^mx3v)v0z91zs%^oy=ul!16_-gcd^malcom"  # noqa: S105

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(strtobool(os.getenv("DEBUG", "False")))

ALLOWED_HOSTS = ["*"]  # TODO: Update this to your domain name  # noqa: TD002

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_distill",
    "commons",
    "accounts",
    "houses",
    "performers",
]

AUTH_USER_MODEL = "accounts.CustomUser"  # noqa: N806
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "malcom.urls"  # noqa: N806
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "commons.context_processors.global_view_additional_context",  # PROVIDES settings.URL_PREFIX to context
            ],
        },
    },
]


WSGI_APPLICATION = "malcom.wsgi.application"  # noqa: N806
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(os.getenv("SQLITE_DB_PATH", "/mnt/data/hakoake-backend/db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "ja"  # noqa: N806
LANGUAGES = [
    ("ja", _("Japanese")),
    ("en", _("English")),
]

TIME_ZONE = "Asia/Tokyo"  # noqa: N806
USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

DEFAULT_URL_PREFIX = ""
URL_PREFIX = os.getenv("DJANGO_URL_PREFIX", DEFAULT_URL_PREFIX)
if URL_PREFIX and not URL_PREFIX.startswith("/"):
    URL_PREFIX = f"/{URL_PREFIX}"
STATIC_URL = f"{URL_PREFIX}/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

WHITENOISE_STATIC_PREFIX = "/static/"  # noqa: N806
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
STATICFILES_DIRS = []

# Media files (user uploads)
MEDIA_URL = f"{URL_PREFIX}/media/"
MEDIA_ROOT = BASE_DIR / "media"


DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")
DJANGO_CORE_LOG_LEVEL = os.getenv("DJANGO_CORE_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} [{levelname:5}] ({name}) {funcName}: {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_CORE_LOG_LEVEL,  # Change to DEBUG to see db queries
        },
        "accounts": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "commons": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "houses": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "performers": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        # add additional apps here
    },
}

AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "ap-northeast-1")
AWS_DEFAULT_REGION = AWS_REGION

# CSRF Settings
# https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-CSRF_COOKIE_HTTPONLY
CSRF_COOKIE_SECURE = False
DEFAULT_CSRF_USE_SESSIONS = "True"  # noqa: N806
CSRF_USE_SESSIONS = bool(strtobool(os.getenv("DJANGO_CSRF_USE_SESSIONS", DEFAULT_CSRF_USE_SESSIONS)))


AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)
LOGIN_URL = "/admin/login/"
# AWS boto3 service endpoints
DEFAULT_BOTO3_S3_SERVICE_ENDPOINT = f"https://s3.{AWS_REGION}.amazonaws.com"
AWS_SERVICE_ENDPOINTS = {
    "s3": os.getenv("BOTO3_S3_SERVICE_ENDPOINT", DEFAULT_BOTO3_S3_SERVICE_ENDPOINT),
    # 他のサービスは必要に応じて追加
}

AWS_S3_ADDRESSING_STYLE = "auto"
if AWS_SERVICE_ENDPOINTS["s3"].startswith("http://"):
    # set s3 addressing style for testing with django-storages
    # -- 'virtual' style not supported by localstack
    AWS_S3_ADDRESSING_STYLE = "path"

assert AWS_S3_ADDRESSING_STYLE in (
    "auto",
    "path",
    "virtual",
)  # https://boto3.amazonaws.com/v1/documentation/api/1.9.42/guide/s3.html#changing-the-addressing-style

AWS_S3_DATA_BUCKETNAME = os.getenv("AWS_S3_DATA_BUCKET_NAME", "malcom-data")
REQUIRED_BUCKETS = (AWS_S3_DATA_BUCKETNAME,)

# YouTube settings
YOUTUBE_CHANNEL_URL = os.getenv("CHANNEL_URL", "")

# Instagram settings (Instagram Login path — graph.instagram.com)
INSTAGRAM_APP_ID = os.getenv("INSTAGRAM_APP_ID", "")
INSTAGRAM_APP_SECRET = os.getenv("INSTAGRAM_APP_SECRET", "")
INSTAGRAM_USER_ID = os.getenv("INSTAGRAM_USER_ID", "")  # populated after first OAuth run

# Threads settings (shares Meta App with Instagram)
THREADS_APP_ID = os.getenv("THREADS_APP_ID", INSTAGRAM_APP_ID)
THREADS_APP_SECRET = os.getenv("THREADS_APP_SECRET", INSTAGRAM_APP_SECRET)
THREADS_USER_ID = os.getenv("THREADS_USER_ID", "")  # populated after first OAuth run

# Local OAuth server cert (generated via mkcert)
OAUTH_LOCALHOST_CERT = BASE_DIR.parent / "localhost.pem"
OAUTH_LOCALHOST_KEY = BASE_DIR.parent / "localhost-key.pem"

PLAYLIST_INTRO_TEXT_GENERATION_MODEL = os.getenv("PLAYLIST_INTRO_TEXT_GENERATION_MODEL", "gemma4:e4b")

# TTS Configuration for video generation
VIDEO_TTS_MODEL = "legraphista/Orpheus:3b-ft-q4_k_m"  # noqa: N806
VIDEO_TTS_VOICE = "tara"  # Orpheus voices: tara, leah, jess, leo, dan, mia, zac, zoe, ceylia
VIDEO_TTS_TEMPERATURE = 0.7  # 0.3-1.5 range
VIDEO_TTS_TOP_P = 0.8  # 0.6-1.0 range  # noqa: N806
VIDEO_TTS_REPETITION_PENALTY = 1.15  # >= 1.1 required for stable generations

# Fallback TTS (edge-tts) configuration
EDGE_TTS_VOICE = "en-US-GuyNeural"  # Microsoft Edge TTS voice (robotic_deep_slow preset)
EDGE_TTS_RATE = "-13%"  # Speech rate modification
EDGE_TTS_PITCH = "-20Hz"  # Pitch modification
EDGE_TTS_STATIC_LEVEL = -15  # Static noise level in dB
EDGE_TTS_BITRATE = "64k"  # Audio bitrate for compression artifacts
EDGE_TTS_SAMPLE_RATE = 16000  # Sample rate for digital artifacts

IMAGE_GENERATION_MODEL = "llava"

# Playlist song selection - duration limits for songs to be eligible
DEFAULT_MIN_SONG_SELECTION_DURATION_SECONDS = 25
MIN_SONG_SELECTION_DURATION_SECONDS = int(
    os.getenv("MIN_SONG_SELECTION_DURATION_SECONDS", DEFAULT_MIN_SONG_SELECTION_DURATION_SECONDS)
)

DEFAULT_MAX_SONG_SELECTION_DURATION_MINUTES = 12
MAX_SONG_SELECTION_DURATION_MINUTES = int(
    os.getenv("MAX_SONG_SELECTION_DURATION_MINUTES", DEFAULT_MAX_SONG_SELECTION_DURATION_MINUTES)
)
