# Generated by Django 5.2.4 on 2025-11-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_monthlyplaylistentry_is_spotlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceschedule',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanceschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
