# Generated by Django 5.2.4 on 2026-01-21 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_alter_performanceschedule_open_time_and_more'),
        ('performers', '0006_add_performer_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True, verbose_name='target date')),
                ('youtube_playlist_id', models.CharField(blank=True, default='', max_length=100)),
                ('youtube_playlist_url', models.URLField(blank=True, default='', max_length=500)),
                ('youtube_channel_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlaylistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_spotlight', models.BooleanField(default=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.weeklyplaylist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performers.performersong')),
            ],
            options={
                'unique_together': {('playlist', 'position')},
            },
        ),
    ]
