# Generated by Django 5.2.4 on 2026-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_weeklyplaylist_weeklyplaylistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='livehousewebsite',
            name='schedule_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
