# Generated by Django 5.2.4 on 2026-04-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_weeklyplaylist_idempotency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceschedule',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text="Crawler source URL for this event's detail page", max_length=500),
        ),
    ]
