# Generated by Django 5.2.4 on 2025-10-29 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0004_performersong_youtube_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='playlist_weight',
            field=models.PositiveIntegerField(default=0, help_text='Used to provide weighting to the MonthlyPlaylist selection'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='performer',
            name='playlist_weight_update_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Updated when playlist_weight is updated'),  # noqa: E501
            preserve_default=False,
        ),
    ]
