# Generated by Django 5.2.4 on 2025-11-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0005_performer_playlist_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Performer/band logo image', null=True, upload_to='performers/logos/'),
        ),
        migrations.AddField(
            model_name='performer',
            name='performer_image',
            field=models.ImageField(blank=True, help_text='Representative performer/band photo', null=True, upload_to='performers/images/'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performer',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performermembersociallink',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performersociallink',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performersong',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
