# Generated by Django 5.2.4 on 2026-02-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0006_add_performer_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='performersociallink',
            name='verified_datetime',
            field=models.DateTimeField(blank=True, default=None, help_text='Date and time when the PerformerSocialLink is verified', null=True),
        ),
    ]
