# Generated by Django 5.2.4 on 2026-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0007_performersociallink_verified_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Performer/band banner image', null=True, upload_to='performers/banners/'),
        ),
        migrations.AddField(
            model_name='performer',
            name='fanart_image',
            field=models.ImageField(blank=True, help_text='Performer/band fanart image', null=True, upload_to='performers/fanart/'),
        ),
    ]
