# Generated by Django 5.2.4 on 2026-02-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0009_deduplicate_performersociallinks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performersociallink',
            unique_together={('performer', 'platform')},
        ),
    ]
