# Generated by Django 5.2.4 on 2026-02-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0010_unique_performer_platform_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='performersociallink',
            name='is_label',
            field=models.BooleanField(default=False),
        ),
    ]
